# ===================================================================
# PLEASE COMPLETE ALL CONFIGURATIONS BEFORE STARTING THE WORKER
# ===================================================================

kuflow:
  api:

    # ID of the APPLICATION configured in KUFLOW.
    # Get it in "Application details" in the Kuflow APP.
    application-id: "29c02bb4-c1dc-4102-81dc-99246922f711"

    # TOKEN of the APPLICATION configured in KUFLOW.
    # Get it in "Application details" in the Kuflow APP.
    token: vrPA*2wR-M5k98?

application:
  temporal:
    # Temporal Namespace. Get it in "Application details" in the KUFLOW APP.
    namespace: "tenant-b8809892-db44-4950-9ad4-70f9ffdf893f"

    # Temporal Queue. Configure it in the "Process definition" in the KUFLOW APP.
    kuflow-queue: "twitterAppQueue"

    mutual-tls:

      # Client certificate
      # Get it in "Application details" in the KUFLOW APP.
      cert-data: |
        -----BEGIN CERTIFICATE-----
        MIIEnTCCAoWgAwIBAgIRAOobe27LBIwi2Djfayu2DX0wDQYJKoZIhvcNAQELBQAw
        NzELMAkGA1UEBhMCRVMxFDASBgNVBAoTC0t1RmxvdyBTLkwuMRIwEAYDVQQDEwlL
        dUZsb3cgQ0EwHhcNMjIwODE4MTA0NzIyWhcNMjcwODE4MTA0NzIyWjA9MTswOQYD
        VQQDEzJBcHBsaWNhdGlvbiAtIDI5YzAyYmI0LWMxZGMtNDEwMi04MWRjLTk5MjQ2
        OTIyZjcxMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOeE98n4KYAy
        1PNECLcDvqVsRZZrFrTxSFxGVnDWUDoszC9NgQjn/NSniNagmj+5ghcsNG2XyTHV
        i/UjEXbPBJVjniCimF6Y39wuMgQsoxzhkbM30lvXqAVyolkLhYqSYJMcMdaWMU7G
        TpxzoRUaC0xcuU9v0zLfj8USwVh1eB1gctbRZxZYauDSfRIebmj3wnqDj3hinPJW
        vai8g8iCRDyRLOT9tGQGrwsAa4JpONyRAZfswXsoFOxKq3zvbb5kA4MFIFBG/Ad1
        mBanVoupmBhDfDdO9Ml+u9HLivoi6YzM9lHLFP1i54IydMdx7FSyy8kzyKoNvgRk
        cJW7qWvZQosCAwEAAaOBnTCBmjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIw
        ADArBgNVHSMEJDAigCDARgciCKivRpe8MPzoBBtHQMpo+CrpKGTG7wFs5KjRLzBN
        BgNVHREERjBEpEIwQDE+MDwGBSvNLAEBDDNrdTphcHBsaWNhdGlvbi8yOWMwMmJi
        NC1jMWRjLTQxMDItODFkYy05OTI0NjkyMmY3MTEwDQYJKoZIhvcNAQELBQADggIB
        AKBNiQ+gXJj38XTvdhVDQHhbl6XxFYr4elJpOOCVfEQQY+a8+4Ub+4zAil3/DB3b
        xecQgCuKVstkzljhB9/zickdybP+eQByL8YCNRyuPKlPpG5cV7Y2fu7DLXUtROH6
        0nMdpAjj32AgQoeqDP9ido0ZV5K0KIyGDnlcC8Yq2rQaJmkT2ZIysalTXOxY/4bn
        6246O0Owpnb75GkyEzvVsUd03QvX5bCGSkY5PNDU7yrMkqeOHc92h26lASwzn65Y
        8NdbaY0r21pExnl4PQebD327BW5R+Odz7WYcK8iskSeSLZOH9lTDb1lmho565wHm
        6EqdaDID20XYY590KRpJagA9uHpilfxmsp8M7TS0txD0xleDrBUpk/F1ZLCImdtF
        /KukFhJbWZ6tAO+4Ydm9qzfh6LMB+Cc3fLmN+2hwZForVTaiZRmLOCNU5WtVfhoL
        WDem9G9Ih7e9ww+9AvPY3q+klyn2SiK6yes0AFPPInvZ2kCJ/VrMPhoeo4/1CSS1
        TDkRB0cu7xLnop+HZOefD405HqKZ8ydPEpo/o3h150CARPkdOmEFBuuwdRSYBtCz
        g3MSP/R6tz9nuUieT8chw0+dmHr9qerajsaq2nJMelOAubw6QOEHzuE+xWwvdrkn
        2jhuYfyjVyF9mB6vr+IIFR0AsAg2B++1n8JV4GJZphhp
        -----END CERTIFICATE-----

      # Private key
      # Get it in "Application details" in the KUFLOW APP.
      # IMPORTANT: This example works with PKCS8, so ensure PKCS8 is selected
      #            when you generate the certificates in the KUFLOW App
      key-data: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnhPfJ+CmAMtTz
        RAi3A76lbEWWaxa08UhcRlZw1lA6LMwvTYEI5/zUp4jWoJo/uYIXLDRtl8kx1Yv1
        IxF2zwSVY54gophemN/cLjIELKMc4ZGzN9Jb16gFcqJZC4WKkmCTHDHWljFOxk6c
        c6EVGgtMXLlPb9My34/FEsFYdXgdYHLW0WcWWGrg0n0SHm5o98J6g494YpzyVr2o
        vIPIgkQ8kSzk/bRkBq8LAGuCaTjckQGX7MF7KBTsSqt8722+ZAODBSBQRvwHdZgW
        p1aLqZgYQ3w3TvTJfrvRy4r6IumMzPZRyxT9YueCMnTHcexUssvJM8iqDb4EZHCV
        u6lr2UKLAgMBAAECggEAPTtAoc0dhMds5M3olCbMZEnneanm/oIWBjmgIQW9gDVa
        52PTLbzVdJS+ry0YvqPckS5iy11qm+CDvJjCxK5p4uzO5Ii8TcCW7E/XcJ0xorDR
        7RllbF70FETGRVCzx/uAyUeasstUTSZLojs+risOM+sOI8FKlVjlWFTmh/PBidr4
        khso+MNfggVYNBmnHSme4f6ExCV1UIsKyTvxMltWz5HVnTXJl5FwVlCQ1wJqQVRn
        tfdTBpG4F2M0xqhXwRcTbOtXB6Kb4IT6P9eM/tOcSja6XbAst/sw8n3CFizCfQs+
        oRafsTcLTIOpYzseMuiOPXI7QDKHgEXhf1+rB0tq4QKBgQDtG+ESM+iAVFofRR5A
        /zKVfGmUDlyDf7MpC6kOfByANQymBp0lsU7RqcfCeuZFWDuRpJWDQaQwTNSCgn3p
        MxI4CSYdWooma5///GETj7wxxIeTE09lCTE5vtv3iYHB0UeikqcY+dJH6g42b84y
        GGqV7lasOgR2X9XIdyO5NLaNuwKBgQD59xWQewukV+hcPlCFOHz/GDkLwRJwnhIj
        50ClhDfnZ1j4BGriXLcCcKvy5eCo70Uhk/k4b8R0o4xe+kd6ReP50qd2075ZHVXq
        RKLpyREj5Xq1oheozEg8h21nVtRWJ+7YapELt192f0zB/A+kWL8eFzwKCxM5ZKTY
        CvZeYblpcQKBgEGK51hkyOxQZOkn7gkBgjYYQgcPQTuIXToHYyAB5s752xk50s7M
        iIEkcXetCWI51Z2Y5Ut3Ja/ETSoWcD+6QlsDDGoo0O916LCWTy9dGCSZsvBQ8i13
        sQfJXny6oge1lhu2dkJNLHd8l5ksps7qOOxhCcxp7Tnbm/jiFhnoHF5pAoGAb7gS
        KEgGVQaBMLEdNd2gaDcAUBOT1Ueg3fEegJuOjNsw9XCsAM3lca6/+0jo1zhRkodb
        TPEPQf5S36RGzAxurxqKhF5w5c1pt9HDam/WPE/1PzbaEjRzWLJCoHw7XOJuKsW+
        XBkyDnko6k5pA1Ay4xUJXYfDqNQlpPWJVXeh8dECgYEA24zcXeVp+yk8P6ntcOeG
        mNFeAkMoMPp7l74HFjlIzZvduKpJd9qyqfrN0FuK367hmhSRAOYvM1Jk5mb1FqdD
        TLzLrO5tjnTZYSiwoDCtG9oAHXqex0nG/SFcEsEYtSmcOLgBQBS0RHlGChwfCKv0
        FfgnscS513SV6Rheen13VpA=
        -----END PRIVATE KEY-----


      # KUFLOW Certification Authority (CA) of the certificates issued in KUFLOW
      ca-data: |
        -----BEGIN CERTIFICATE-----
        MIIFRjCCAy6gAwIBAgIQc7f/lTiGhaHPQeNBbanfeDANBgkqhkiG9w0BAQsFADA3
        MQswCQYDVQQGEwJFUzEUMBIGA1UEChMLS3VGbG93IFMuTC4xEjAQBgNVBAMTCUt1
        RmxvdyBDQTAeFw0yMTExMDMwOTM1MzRaFw00MTExMDMwOTM1MzRaMDcxCzAJBgNV
        BAYTAkVTMRQwEgYDVQQKEwtLdUZsb3cgUy5MLjESMBAGA1UEAxMJS3VGbG93IENB
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzX0wIVK6kVu5ykpC3ki9
        JT5JIypjn2WBM+XYn/kDDJEDdps7o0REGEIHy5JrR3QGhlvIWjahCRF76uM+yt29
        L31kO6Mu3AxCHYzcGayE+HHwtj8g9Rf8E4zRmOanCeNUZLNCjm/CVFwAs0pBS9/p
        nJDlnCitavOEArEC9yinO5R0biQzXn2fpffgfyFXzw65StffHCn+Hnyn3JJLha5/
        pqmOZ5b6IHTwdSajbBt0gzfi2XebjfG+nLrxhl+C7ghtMc80zlBh8fS+ZJinF2TV
        EQoJHduTJRyWffkSqCLPiB7E4MZYJe9wsjeagjlQzL3oTVf5xbh++M0M581Gy3Aa
        sGyw/MGseCtiHv68VWViYLskcpBRw0fwqTT0aRaTRBT/emPYDPdeyWY1PRfWWV33
        kYkhdsLDg4LaK1NOeHLeX0/UZpre43/tWSwrvhFzNcCt0CYEcdS6c7+cd0YR5VG5
        qNNWTB1Bp9w+sYJAzfW0zBeBiHKb/yBPGoG8q7/MaWvipEa5CmfMTRV+pRb7DiHZ
        rTQcZcpXV5RffXG5zGCYVjiyBpfD7zaWEoWXo3KNWEZKE2De5fzTXgGprdvKnmGU
        WaeJnZuG9Z8HeKQZ/4qhLrWrXcMuXmdioatSf/TflKFsfkcCpKMLrY9pZ6X+sl+n
        sO+ChIYtn7uoXGJMBQf4NkcCAwEAAaNOMEwwDgYDVR0PAQH/BAQDAgKkMA8GA1Ud
        EwEB/wQFMAMBAf8wKQYDVR0OBCIEIMBGByIIqK9Gl7ww/OgEG0dAymj4KukoZMbv
        AWzkqNEvMA0GCSqGSIb3DQEBCwUAA4ICAQAARDbBUG7+Vna7YaTipc7ilLwnS0fY
        n0f8+37UVTzeRaJrqCqruSgUhQ9Lj9pyprj73u/g/gkU+iy4MHHW0ZCM8xbbqqcm
        0rviYFusk8UutBXCFSKp0WHKC8RULGGIB8+Zvcq2ViH0pQwfJtY1Ifpoi/9tTuWb
        Kwhe0pM/VyEJHznH0ChfO/8SY96jQqMZ0vo5g5V7rwy0fbdXk9CB12/0/pEc1/dC
        iQ95RyfjcN9SEGRPKbrrm3HkOTRxPQlugKH77LHT35XOJ17z93AeA+r2ub5LZgfQ
        jkVtbZOVW01j8rvHiSOI+nY0ETgFmH2aGb5Qco9zH4FPzjzwz3GYlzJsv0Uutj5B
        ZFBtk91J4ec1y/4wU4ljIk9SgMeRTAGocY/asQ8uiE1Zi/dNu5i0kF0vmtXyltne
        mPwLZ8KmYSAB0Me06qxkFFM/lxTu/GUczto5UgJzMU9yliXSfTm5oxEat5kvvFgf
        sfYAZV9zjBe9DANfhDjcGP8lWuk2uHd/nPUcWD18B3pWqBuVQ7XyE2cpDgphNsgJ
        nCB1vZ+is1seIY9NUBWXfJjzjXPBjf5lanPEFJjcsc12BrrAw1vmXa+t3d6wF0hj
        tTh1u3ohM5yGEg7M1beZVXu4TmWiYhGpS9y9kT6Wp+Uzb2/J5A92PCHrT77+7Fcp
        OyxvHLMCIfAhGw==
        -----END CERTIFICATE-----
